	<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MarkdownViewer.Wpf" Version="1.0.2924" />
  </ItemGroup>


  <ItemGroup>
    <None Update="SampleMarkdown.md" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Assets\sample-image.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
